In [30]:
from sklearn.model_selection import cross_validate, LeaveOneGroupOut
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import networkx as nx


In [ ]:
# Populate the graph with edges and attributes
graphs = {}
for _, row in df.iterrows():
    # Check if graph_id exists, if not create a new DiGraph
    if row['graph_id'] not in graphs:
        graphs[row['graph_id']] = nx.DiGraph()
    G = graphs[row['graph_id']]
    
    # Add an edge if is_causal is True
    if row['is_causal']: 
        G.add_edge(row['edge_source'], row['edge_dest'])
    else:
        G.add_node(row['edge_source'])
        G.add_node(row['edge_dest'])


NameError: name 'df' is not defined

In [27]:
from graphviz import Digraph

for key, graph in graphs.items():
    G_dot = Digraph(engine="dot",format='png')

    for node in graph.nodes():
        G_dot.node(str(node))
    for edge in graph.edges():
        G_dot.edge(str(edge[0]), str(edge[1]))

    # Render the graph in a hierarchical layout
    G_dot.render(f"pics/graph_{key}.png", view=False)

In [63]:
#load dags.pkl
import pickle
with open('dags.pkl', 'rb') as f:
    dags = pickle.load(f)

    

In [29]:
from graphviz import Digraph

for key, graph in enumerate(dags):
    G_dot = Digraph(engine="dot",format='png')

    for node in graph.nodes():
        G_dot.node(str(node))
    for edge in graph.edges():
        G_dot.edge(str(edge[0]), str(edge[1]))

    # Render the graph in a hierarchical layout
    G_dot.render(f"pics/{key}_graph.png", view=False)

# Checking the Observations

# Reconstructing the formula

In [4]:
[(i, j) for i in range(3) for j in range(3)]

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [3]:
import numpy as np
np.round(np.random.uniform(low=-1, high=1),2)

0.35

In [8]:
import pickle

In [15]:
#load observations.pkl
with open('../data/ts.pkl', 'rb') as f:
    observations, dags, updated_dags = pickle.load(f)
    

In [ ]:
choe

In [15]:
D = observations[0]
D

0        1        2        3        4        5
0    0.23677 -0.23508  0.96646 -0.06647  0.71988  0.36062
1   -0.09900 -0.97347  0.88440  0.12658 -0.22917 -0.96807
2   -0.53821 -0.51795  0.36653  0.21999  0.66639 -0.65327
3    0.15854 -0.19529  0.45805  0.59840 -0.82611 -0.25965
4    0.15204  0.90743  0.26426  0.33110 -0.75462  0.41011
..       ...      ...      ...      ...      ...      ...
147  0.00151 -0.01244 -0.00007  0.00372 -0.01448  0.00774
148  0.00188 -0.00481 -0.00027 -0.00422 -0.00683  0.00114
149 -0.00077 -0.00008  0.00235  0.00411  0.00674 -0.00553
150  0.00137  0.01398  0.00057 -0.00130  0.01450 -0.00770
151 -0.00204 -0.00227 -0.00119  0.00909  0.00128 -0.00333

[152 rows x 6 columns]

In [18]:
import sys
sys.path.append("../d2c")
from utils import dag_to_formula

In [20]:
dag = updated_dags[0]


dag_to_formula(dag)



0 = -0.16629*0_t-1 + -0.35713*0_t-2 + 0.15089*0_t-3 + 0
2 = -0.44359*2_t-1 + 0.222*2_t-2 + 0.43855*2_t-3 + 0
3 = 0.29654*2_t-1 + 0.29654*2_t-2 + 0.29654*2_t-3 + -0.49922*3_t-1 + 0.49221*3_t-2 + 0.11748*3_t-3 + 0
4 = -0.31657*2_t-1 + -0.31657*2_t-2 + -0.31657*2_t-3 + 0.09685*3_t-1 + 0.09685*3_t-2 + 0.09685*3_t-3 + 0.11165*4_t-1 + -0.49293*4_t-2 + -0.47694*4_t-3 + 0
1 = 0.27969*3_t-1 + 0.27969*3_t-2 + 0.27969*3_t-3 + -0.40003*4_t-1 + -0.40003*4_t-2 + -0.40003*4_t-3 + 0.02477*1_t-1 + -0.10014*1_t-2 + -0.45333*1_t-3 + 0
5 = -0.05417*3_t-1 + -0.05417*3_t-2 + -0.05417*3_t-3 + -0.04075*4_t-1 + -0.04075*4_t-2 + -0.04075*4_t-3 + 0.47376*5_t-1 + -0.26723*5_t-2 + -0.40939*5_t-3 + 0



In [21]:
observations

[           0        1        2        3        4        5
 0    0.23677 -0.23508  0.96646 -0.06647  0.71988  0.36062
 1   -0.09900 -0.97347  0.88440  0.12658 -0.22917 -0.96807
 2   -0.53821 -0.51795  0.36653  0.21999  0.66639 -0.65327
 3    0.15854 -0.19529  0.45805  0.59840 -0.82611 -0.25965
 4    0.15204  0.90743  0.26426  0.33110 -0.75462  0.41011
 ..       ...      ...      ...      ...      ...      ...
 147  0.00151 -0.01244 -0.00007  0.00372 -0.01448  0.00774
 148  0.00188 -0.00481 -0.00027 -0.00422 -0.00683  0.00114
 149 -0.00077 -0.00008  0.00235  0.00411  0.00674 -0.00553
 150  0.00137  0.01398  0.00057 -0.00130  0.01450 -0.00770
 151 -0.00204 -0.00227 -0.00119  0.00909  0.00128 -0.00333
 
 [152 rows x 6 columns],
            0        1        2        3        4        5
 0   -0.06377  0.90948  0.11156  0.29944  0.16175 -0.66224
 1    0.03081  0.05001  0.01152 -0.53703 -0.35947  0.41726
 2   -0.01549  0.00095 -0.00081  0.32039  0.07259 -0.37101
 3    0.00711 -0.00037  0.000

In [22]:
exploding_series = []
for obs_index, observation in enumerate(observations):
    for value in observation.iloc[-1]:
        if abs(value) > 1000:
            exploding_series.append(obs_index)

        

In [23]:
exploding_series

[19,
 19,
 35,
 35,
 35,
 35,
 37,
 37,
 37,
 37,
 38,
 38,
 38,
 38,
 39,
 39,
 42,
 42,
 42,
 48,
 48]

In [66]:
# Using list comprehension to filter the elements
filtered_observations = [observations[i] for i in range(len(observations)) if i not in exploding_series]
filtered_dags = [dags[i] for i in range(len(dags)) if i not in exploding_series]
filtered_updated_dags = [updated_dags[i] for i in range(len(updated_dags)) if i not in exploding_series]


In [69]:
len(filtered_observations)

44

In [70]:
#pickle again 
with open('filtered_observations.pkl', 'wb') as f:
    pickle.dump(filtered_observations, f)

with open('filtered_dags.pkl', 'wb') as f:
    pickle.dump(filtered_dags, f)

with open('filtered_updated_dags.pkl', 'wb') as f:
    pickle.dump(filtered_updated_dags, f)



In [24]:
from statsmodels.tsa.api import VAR
import numpy as np
#np from txt
data = np.loadtxt('../causeme/experiments/linear-VAR_N-3_T-150_0198.txt')
# Fit the VAR model
model = VAR(data)
results = model.fit(maxlags=5, ic='aic')
print(results.params)


[[ 0.20921354  0.19466644  0.03685556]
 [ 0.80976437 -0.02165628  0.07613718]
 [ 0.1304932   0.95714291  0.04572878]
 [-0.06123438  0.02061111  0.39562886]
 [ 0.07480246  0.14377912  0.11043204]
 [-0.08990433 -0.13905322 -0.00875466]
 [ 0.19277196 -0.03335154 -0.07197485]]


# DAGs

In [2]:
# randomly at 50/50
import networkx as nx
G = nx.DiGraph()
for i in range(5):
    G.add_node(i)


In [ ]:
#load observations.pkl
with open('../data/ts.pkl', 'rb') as f:
    observations, dags, updated_dags = pickle.load(f)
    

In [16]:
from graphviz import Digraph

for key, graph in enumerate(updated_dags):
    G_dot = Digraph(engine="dot",format='png')

    for node in graph.nodes():
        G_dot.node(str(node))
    for edge in graph.edges():
        G_dot.edge(str(edge[0]), str(edge[1]))

    # Render the graph in a hierarchical layout
    G_dot.render(f"pics/{key}_graph.png", view=False)